version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://hapi-fhir-postgres:5432/FHIR_db"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
    depends_on:
      hapi-fhir-postgres:
        condition: service_healthy
    ports:
      - "8080:8080"


  hapi-fhir-postgres:
    image: postgres:15-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "FHIR_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "FHIR_db" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  hapi-fhir-postgres:
